requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    submodule: true
  - https://github.com/pyexcel/pyexcel-mobans
configuration:
  configuration_dir: "pyexcel-mobans:config"
  template_dir:
  - "pyexcel-mobans:templates"
  - "pypi-mobans:templates"
  - ".moban.d"
  configuration: pyexcel-xls.yml
targets:
  - README.rst: README.rst
  - setup.py: setup.py
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - .travis.yml: travis.yml
  - requirements.txt: requirements.txt
  - .gitignore: gitignore.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - test.sh: test.script.jj2
  - test.bat: test.script.jj2
  - "tests/test_filter.py": "tests/test_filter.py.jj2"
  - "tests/test_formatters.py": "tests/test_formatters.py.jj2"
  - "tests/test_stringio.py": "tests/test_stringio.py.jj2"
  - "tests/test_writer.py": "tests/test_writer.py.jj2"
  - "tests/base.py": "tests/base.py"
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
